
-- 添加左右值和层级索引
CREATE INDEX idx_dept_tree ON departments (left_value, right_value, level);

-- 添加部门状态索引
CREATE INDEX idx_dept_status ON departments (status);

-- 添加复合索引
CREATE INDEX idx_dept_parent_status ON departments (parent_id, status);


INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565660, 0, 0, '', '', 36, '010506', '设置部门管理员', 'menu.set.admin', '', '', 6, 1, '', '', 1, 23, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563356, 1740563368, 0, '', '', 13, '0103', '角色管理', 'menu.authority.role', '', '', 3, 1, 'role', '', 1, 1, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740561595, 0, 0, '', '', 3, '0102', '租户管理', 'menu.authority.tenant', '', '', 2, 1, 'tenant', '', 1, 1, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740562142, 0, 0, '', '', 4, '010201', '新增', 'menu.add', '', '', 1, 2, '', '', 1, 3, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1737032516, 1740562169, 0, '', '', 1, '01', '权限管理', 'menu.authority', 'icon-user', '', 2, 1, 'authority', '', 1, 0, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740562227, 0, 0, '', '', 5, '010202', '修改', 'menu.edit', '', '', 2, 2, '', '', 1, 3, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740562382, 0, 0, '', '', 6, '010203', '删除', 'menu.delete', '', '', 3, 2, '', '', 1, 3, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740562543, 0, 0, '', '', 7, '010204', '分配权限', 'menu.assign.permissions', '', '', 4, 2, '', '', 1, 3, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740562765, 0, 0, '', '', 8, '010205', '获取租户权限', '', '', '', 5, 3, '', '', 1, 3, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563107, 0, 0, '', '', 10, '010102', '修改', 'menu.edit', '', '', 2, 2, '', '', 1, 2, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563060, 1740563123, 0, '', '', 9, '010101', '新增', 'menu.add', '', '', 1, 1, '', '', 1, 2, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1737032623, 1740563131, 0, '', '', 2, '0101', '用户管理', 'menu.authority.user', '', '', 1, 1, 'user', '', 1, 1, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563195, 0, 0, '', '', 11, '010103', '删除', 'menu.delete', '', '', 3, 2, '', '', 1, 2, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563260, 0, 0, '', '', 12, '010105', '更新用户状态', 'menu.update.status', '', '', 5, 2, '', '', 1, 2, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563452, 0, 0, '', '', 14, '010301', '新增', 'menu.add', '', '', 1, 2, '', '', 1, 13, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565236, 1740565309, 0, '', '', 31, '010501', '新增', 'menu.add', '', '', 1, 1, '', '', 1, 23, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565913, 0, 0, '', '', 37, '0106', '组织人员', 'menu.authority.organization', '', '', 6, 1, 'organization', '', 1, 1, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563530, 1740563570, 0, '', '', 15, '010302', '修改', 'menu.edit', '', '', 2, 1, '', '', 1, 13, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563616, 0, 0, '', '', 16, '010303', '删除', 'menu.delete', '', '', 3, 1, '', '', 1, 13, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563658, 0, 0, '', '', 17, '010304', '角色详情', '', '', '', 4, 3, '', '', 1, 13, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563762, 0, 0, '', '', 18, '0104', '系统权限', 'menu.authority.permission', '', '', 4, 1, 'permission', '', 1, 1, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563824, 0, 0, '', '', 19, '010401', '新增', 'menu.add', '', '', 1, 2, '', '', 1, 18, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563859, 0, 0, '', '', 20, '010402', '修改', 'menu.edit', '', '', 2, 2, '', '', 1, 18, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563905, 0, 0, '', '', 21, '010403', '删除', 'menu.delete', '', '', 3, 2, '', '', 1, 18, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740563995, 0, 0, '', '', 22, '010404', '权限详情', 'menu.details', '', '', 4, 2, '', '', 1, 18, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564514, 0, 0, '', '', 23, '0105', '组织机构', 'menu.authority.organization', '', '', 5, 1, 'organization', '', 1, 1, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564591, 0, 0, '', '', 24, '02', '仪表盘', '', 'icon-dashboard', '', 2, 1, 'dashboard', '', 1, 0, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564633, 0, 0, '', '', 25, '0201', '工作台', 'menu.dashboard.workplace', '', '', 1, 1, 'workplace', '', 1, 24, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564677, 0, 0, '', '', 26, '0202', '系统监控', 'menu.monitor.system', '', '', 2, 1, 'systemMonitor', '', 1, 24, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564733, 0, 0, '', '', 27, '03', '日志管理', 'menu.log', 'icon-file', '', 3, 1, 'log', '', 1, 0, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564813, 0, 0, '', '', 28, '0301', '管理员登录日志', 'menu.log.admin', '', '', 1, 1, 'adminLogList', '', 1, 27, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564854, 0, 0, '', '', 29, '0302', '用户登录日志', 'menu.log.app', '', '', 2, 1, 'appLogList', '', 1, 27, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740564910, 0, 0, '', '', 30, '0303', '操作日志', 'menu.log.operation', '', '', 3, 1, 'operationLogList', '', 1, 27, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565349, 0, 0, '', '', 32, '010502', '修改', 'menu.edit', '', '', 2, 2, '', '', 1, 23, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565407, 0, 0, '', '', 33, '010503', '删除', 'menu.delete', '', '', 3, 2, '', '', 1, 23, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565514, 0, 0, '', '', 34, '010504', '详情', 'menu.details', '', '', 4, 2, '', '', 1, 23, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565574, 0, 0, '', '', 35, '010505', '获取部门树', 'menu.get_tree', '', '', 5, 2, '', '', 1, 23, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740565988, 0, 0, '', '', 38, '010601', '分配部门', 'menu.assign.user', '', '', 1, 2, '', '', 1, 37, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740566031, 0, 0, '', '', 39, '010602', '移除用户', 'menu.remove.user', '', '', 2, 1, '', '', 1, 37, '');
INSERT INTO public.sys_permissions (created_at, updated_at, deleted_at, creator, updater, id, code, name, localize, icon, description, sequence, type, path, properties, status, parent_id, parent_path) VALUES (1740566110, 0, 0, '', '', 40, '010603', '人员调动', 'menu.user.transfer', '', '', 3, 2, '', '', 1, 37, '');
